### ISSUE TITLE
Grunt: No such file

### ISSUE THREAD

**Issue by alexkrenz** [Eluinhost/TeamspeakAuth#84]
Hi,
when i use the grunt install command i get the following error:
`root@web:/home/auth/TeamspeakAuth-master# grunt install
/usr/bin/env: node: No such file or directory`

And if i skip this step i can use the composer command but the next ohne gives me this error:
`alex@web:/home/auth/TeamspeakAuth-master$ php bin/console cache:clear --env=prodPHP Warning:  require_once(/home/auth/TeamspeakAuth-master/bin/../var/bootstrap.php.cache): failed to open stream: No such file or directory in /home/auth/TeamspeakAuth-master/bin/console on line 10
PHP Fatal error:  require_once(): Failed opening required '/home/auth/TeamspeakAuth-master/bin/../var/bootstrap.php.cache' (include_path='.:/usr/share/php:/usr/share/pear') in /home/auth/TeamspeakAuth-master/bin/console on line 10`

Could you help me please? 

Thanks :)

**Comment by RhvsW** [comment]
If you're on a debian based system install the nodejs-legacy package.

**Comment by Eluinhost** [comment]
The first looks what @MeltedLux says, debian installs as `nodejs` not `node`. I use `nvm` myself for managing/using multiple versions of node, it'll probably be useful in this case. Are you sure you ran the `composer install` and that it completed correctly? It could also be the issue fixed in df4a25ac2cf231905ab3ebdd994b059d36de2d69 so make sure you have a `var` folder in the project so symfony finds the correct folder structure

**Comment by alexkrenz** [comment]
Hi,
thanks for your help. Now grunt install works but now I have a new Problem:
If I run `php bin/console cache:clear --env=prod`, I get this error:

`root@web:/home/auth/TeamspeakAuth-master# php bin/console cache:clear --env=prod
PHP Warning:  require_once(/home/auth/TeamspeakAuth-master/bin/../var/bootstrap.php.cache): failed to open stream: No such file or directory in /home/auth/TeamspeakAuth-master/bin/console on line 10
PHP Fatal error:  require_once(): Failed opening required '/home/auth/TeamspeakAuth-master/bin/../var/bootstrap.php.cache' (include_path='.:/usr/share/php:/usr/share/pear') in /home/auth/TeamspeakAuth-master/bin/console on line 10`

It searches for the files not in TeamspeakAuth/var rather in TeamspeakAuth/bin/../var. And I'm too dumb to fix this myself ^^

**Comment by Eluinhost** [comment]
`TeamspeakAuth/var` is the same folder as `TeamspeakAuth/bin/../var`. If I remember correctly the var folder was missing so Symfony was thinking it was the older structure during `composer install` and didn't fill stuff out correctly. Can you make sure you have a `var` folder and then run `composer install` again and see if it works? Then you should be able to clear the cache normally

**Comment by alexkrenz** [comment]
My hoster moved my server and there were some issues so i installed ubuntu 16.04 on my server now (before i had Debian 8). Before there was an var folder and i couldn't see any issues after running composer install.

Now on Ubuntu 16.04 everything worked finde, but then grunt again...

```
Running "clean:bower" (clean) task

Running "bower-install-simple" task
Install Bower Dependencies
bower error         Path must be a string. Received undefined

Stack trace:
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at Project._readInstalled (/root/TeamspeakAuth/node_modules/bower/lib/core/Project.js:589:26)
    at Project._analyse (/root/TeamspeakAuth/node_modules/bower/lib/core/Project.js:461:14)
    at Project.install (/root/TeamspeakAuth/node_modules/bower/lib/core/Project.js:48:17)
    at install (/root/TeamspeakAuth/node_modules/bower/lib/commands/install.js:27:20)
    at /root/TeamspeakAuth/node_modules/bower/lib/commands/index.js:21:32
    at Promise.apply (/root/TeamspeakAuth/node_modules/q/q.js:1078:26)
    at Promise.promise.promiseDispatch (/root/TeamspeakAuth/node_modules/q/q.js:741:41)
    at /root/TeamspeakAuth/node_modules/q/q.js:1304:14

Console trace:
Trace
    at StandardRenderer.error (/root/TeamspeakAuth/node_modules/bower/lib/renderers/StandardRenderer.js:82:17)
    at Logger.<anonymous> (/root/TeamspeakAuth/node_modules/grunt-bower-install-simple/tasks/grunt-bower-install-simple.js:81:22)
    at emitOne (events.js:77:13)
    at Logger.emit (events.js:169:7)
    at Logger.emit (/root/TeamspeakAuth/node_modules/bower-logger/lib/Logger.js:29:39)
    at /root/TeamspeakAuth/node_modules/bower/lib/commands/index.js:40:20
    at _rejected (/root/TeamspeakAuth/node_modules/q/q.js:797:24)
    at /root/TeamspeakAuth/node_modules/q/q.js:823:30
    at Promise.when (/root/TeamspeakAuth/node_modules/q/q.js:1035:31)
    at Promise.promise.promiseDispatch (/root/TeamspeakAuth/node_modules/q/q.js:741:41)

System info:
Bower version: 1.3.12
Node version: 4.2.6
OS: Linux 4.4.0-38-generic x64
Warning: Task "bower-install-simple" failed. Use --force to continue.

Aborted due to warnings.
```

Could you help me. If you have time maybe in teamspeak or skype?
